### ISSUE TITLE
Can any one help, Thanks!

### ISSUE THREAD

**Issue by leoliuasia** [metasys-server/basic-services-dotnet#117]
## Login was successful, but call other apis, always return message: 
{
    "Message": "Insufficient permissions for this request."
}

# Is there something I was missing?

{
  "Issuer": "192.168.1.249",
  "IssuedTo": "api1",
  "Token": "Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ii1NbGEzZkFRMjZYQV9iYV9jUTgzSUdlRDNGTSIsImtpZCI6Ii1NbGEzZkFRMjZYQV9iYV9jUTgzSUdlRDNGTSJ9.eyJpc3MiOiJodHRwOi8vbG9jYWxob3N0Ojk1MDYvQVBJLkF1dGhlbnRpY2F0aW9uU2VydmljZSIsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTUwNi9BUEkuQXV0aGVudGljYXRpb25TZXJ2aWNlL3Jlc291cmNlcyIsImV4cCI6MTYwOTkyNjkwNywibmJmIjoxNjA5OTI1MTA3LCJjbGllbnRfaWQiOiJtZXRhc3lzX2FwaSIsInNjb3BlIjpbIm1ldGFzeXNfYXBpIiwib2ZmbGluZV9hY2Nlc3MiLCJvcGVuaWQiXSwic3ViIjoiMTJlMTBkYzQtNWM0OC00ZmI4LWJiNmItMzBkMzM3MjY2OWNmIiwiYXV0aF90aW1lIjoxNjA5OTI1MTA3LCJpZHAiOiJpZHNydiIsIlVzZXJJZCI6IjYiLCJVc2VyTmFtZSI6ImFwaTEiLCJJc0FkbWluIjoiVHJ1ZSIsIklzUGFzc3dvcmRDaGFuZ2VSZXF1aXJlZCI6IlRydWUiLCJJc1Rlcm1zQW5kQ29uZGl0aW9uc1JlcXVpcmVkIjoiVHJ1ZSIsIkN1bHR1cmUiOiJlbi1VUyIsIkFjdGl2ZUxpY2Vuc2VzIjoiW3tcImZlYXR1cmVcIjp7XCJuYW1lXCI6XCJBRFhcIixcInZlcnNpb25cIjpcIjExLnhcIn0sXCJJdGVtXCI6MyxcInN0YXR1c1wiOjEsXCJleHBpcnlEYXRlXCI6XCIyMDIxLTAzLTI4VDIzOjU5OjU5KzAwOjAwXCIsXCJkYXlzVG9FeHBpcmVcIjo4MixcIlR5cGVcIjoxfSx7XCJmZWF0dXJlXCI6e1wibmFtZVwiOlwiTU9OQ01ELUFQSVwiLFwidmVyc2lvblwiOlwiMTEueFwifSxcIkl0ZW1cIjoxNyxcInN0YXR1c1wiOjEsXCJleHBpcnlEYXRlXCI6XCIyMDIxLTEyLTI4VDIzOjU5OjU5KzAwOjAwXCIsXCJkYXlzVG9FeHBpcmVcIjozNTcsXCJUeXBlXCI6MX0se1wiZmVhdHVyZVwiOntcIm5hbWVcIjpcIkZBVUxUXCIsXCJ2ZXJzaW9uXCI6XCIxMS54XCJ9LFwiSXRlbVwiOjIxLFwic3RhdHVzXCI6MixcImV4cGlyeURhdGVcIjpcIjAwMDEtMDEtMDFUMDA6MDA6MDBcIixcImRheXNUb0V4cGlyZVwiOjAsXCJUeXBlXCI6MH0se1wiZmVhdHVyZVwiOntcIm5hbWVcIjpcIlRSSUFHRVwiLFwidmVyc2lvblwiOlwiMTEueFwifSxcIkl0ZW1cIjoyMixcInN0YXR1c1wiOjIsXCJleHBpcnlEYXRlXCI6XCIwMDAxLTAxLTAxVDAwOjAwOjAwXCIsXCJkYXlzVG9FeHBpcmVcIjowLFwiVHlwZVwiOjB9LHtcImZlYXR1cmVcIjp7XCJuYW1lXCI6XCJBREZTXCIsXCJ2ZXJzaW9uXCI6XCIxMS54XCJ9LFwiSXRlbVwiOjIzLFwic3RhdHVzXCI6MixcImV4cGlyeURhdGVcIjpcIjAwMDEtMDEtMDFUMDA6MDA6MDBcIixcImRheXNUb0V4cGlyZVwiOjAsXCJUeXBlXCI6MH1dIiwiYW1yIjpbInBhc3N3b3JkIl19.MWWLv7NdyCOHk6bI6BWb_uPCUFaT6KoBous0gOe9645SBdqT6vIaQyahi9fof9r7_1VuPKKfA1IoeNSPL856h4pbcejFP6RXVKkw_KZOxfjZ5ymHAb42iFwggv8lHY5k-AzVp7S6H-QOReJhzVJqKXvpizybzdsbdU1fPMN-7fxBh7GnsVxELJmPCIR62xbyuPvF-JVdZdYlM8zuT5UOd_r_rrNw9f6Ru-Tk9ACO5NHOOgg8nGhLCmMQodVK3Bkg1fJrEmwHKcphIW_URZQUxNyOX_wgOnMTaGaGXKeh-NfmO6HT3PkuvopTlpNfc18e00M0QvurT2wfxkFm4U5PjQ",
  "Expires": "2021-01-06T09:55:07Z"
}

Unhandled exception. JohnsonControls.Metasys.BasicServices.MetasysHttpException: Call failed with status code 403 (Forbidden): GET https://192.168.1.249/api/v2/audits?OriginApplications=1%2C6&ClassLevels=0&ActionTypes=1%2C5&StartTime=2020-05-20T00%3A00%3A00&EndTime=2021-06-03T00%3A00%3A00
   at JohnsonControls.Metasys.BasicServices.BasicServiceProvider.ThrowHttpException(FlurlHttpException e)
   at JohnsonControls.Metasys.BasicServices.BasicServiceProvider.GetRequestAsync(String resource, Dictionary`2 parameters, Object[] pathSegments)
   at JohnsonControls.Metasys.BasicServices.BasicServiceProvider.GetPagedResultsAsync[T](String resource, Dictionary`2 parameters, Object[] pathSegments)
   at JohnsonControls.Metasys.BasicServices.AuditServiceProvider.GetAsync(AuditFilter auditFilter)
   at JohnsonControls.Metasys.BasicServices.AuditServiceProvider.Get(AuditFilter auditFilter)
   at adsapidemo.Program.Main(String[] args) in C:\Users\Leo\Desktop\adsapidemo\Program.cs:line 28

Unhandled exception. JohnsonControls.Metasys.BasicServices.MetasysHttpException: Call failed with status code 403 (Forbidden): GET https://192.168.1.249/api/v3/networkDevices/availableTypes
   at JohnsonControls.Metasys.BasicServices.BasicServiceProvider.ThrowHttpException(FlurlHttpException e)
   at JohnsonControls.Metasys.BasicServices.MetasysClient.GetResourceTypesAsync(String resource, String pathSegment)
   at JohnsonControls.Metasys.BasicServices.MetasysClient.GetNetworkDeviceTypesAsync()
   at JohnsonControls.Metasys.BasicServices.MetasysClient.GetNetworkDeviceTypes()
   at adsapidemo.Program.Main(String[] args) in C:\Users\Leo\Desktop\adsapidemo\Program.cs:line 21

## Source Code:
`
 var client = new MetasysClient("192.168.1.249", true, ApiVersion.v2);
// client.Version = ApiVersion.v3;
AccessToken accessToken = client.TryLogin("api1", "aP@0104-le");
Console.WriteLine(accessToken);
AuditFilter auditFilter = new AuditFilter
{
    StartTime = new DateTime(2020, 5, 20),
    EndTime = new DateTime(2021, 6, 3),
    OriginApplications = OriginApplicationsEnum.SystemSecurity | OriginApplicationsEnum.AuditTrails,
    ActionTypes = ActionTypeEnum.Subsystem | ActionTypeEnum.Command
};
PagedResult<Audit> auditsPager = client.Audits.Get(auditFilter);

// Prints the number of records fetched and paging information
Console.WriteLine("Total:" + auditsPager.Total);
Console.WriteLine("Current page:" + auditsPager.CurrentPage);
Console.WriteLine("Page size:" + auditsPager.PageSize);
Console.WriteLine("Pages:" + auditsPager.PageCount);

foreach (var item in client.GetNetworkDeviceTypes())
{
    Console.WriteLine(item.Id);
}
`

**Comment by michaelgwelch** [comment]
The biggest issues clients have are

1. Not using an API User
2. Not having logged in and accepted Terms and Conditions via MUI or SMP prior to using the account for API access.
