### ISSUE TITLE
A question about JWT expire time.

### ISSUE THREAD

**Issue by 285209649** [metasys-server/basic-services-dotnet#131]
The issue is about Metasys API JWT expire time.

My team try to use the Metasys API in China with +8 time zone. But the token was expired 3 hours when we got it，so we can't use any API with the expired token.
I try to set and sync Metasys server time, the server time was sync to the Windows with a correct time.But the token still expired for 3 hours.
But when I set the server time to 4 hours earlier(before the token expired)，everything works well.

So,How to extend the validity time of the token?
Or how to sync the server time(may be JWT sending component is diffrent from Metasys main server?) who send me the token, to ensure I get a valid token.
Thanks.

**Comment by michaelgwelch** [comment]
Thanks for your question. I'll forward it to our support team.

**Comment by michaelgwelch** [comment]
Some questions:

1. Are you using the API directly or are you using this basic-services-dotnet client?
2. What version of Metasys are you using?

If you are using the API directly can you post some responses to the `login` (please hide your access token). So include an example of the expiration time that is returned by the API and also document what time you tried to `login` so I can see the issues.

**Comment by 285209649** [comment]
> 

1.I use the API directly with an API test tool like Postman.
2.Metasys 11.0 and Metasys API v3

The following are the responses from the server 
Response code :200 success
Response headers:
Cache-Control :private
Pragma:no-cache,no-cache
Content-Type:application/vnd.metasysapi.v3+json
Expires:-1
Set-Cookie:Secure; HttpOnly
Strict-Transport-Security:max-age=31536000
X-Content-Type-Options:nosniff
X-XSS-Protection:1; mode=block
Date:Tue, 04 Apr 2023 02:41:34 GMT   //The request time: 04 Apr 2023 10:41:34 UTC +8
Content-Length:2241

Response :
{"accessToken":"**HIDEN**","expires":"2023-04-04T07:39:39Z"// Invalid token expired 3 hours ago from 04 Apr 2023 10:41:34 UTC +8}

**Comment by michaelgwelch** [comment]
Thanks for that information especially the headers to make it clear the time of the request vs the expiration time.

**Comment by 285209649** [comment]
I planned to make a screen record today to illustrate the situation.Betore I record the screen, I try to reset the server(ADX) time zone and restart the server.Then when I start record, the API WORKS WELL!  Maybe the time zone setting and restart behavior reset the server time? But it looks like the problem has been solved anyway.I'm looking forward to explore more usage of the Metasys API. ^^
