### ISSUE TITLE
Set up CI for repository including contributing information.

### ISSUE THREAD

**Issue by mgwelch** [metasys-server/basic-services-dotnet#15]
I recommend that we use GitHub Actions for this. It's currently in beta. I've been accepted into the beta, so I'm hoping that means that this repo will be able to use them. It works a lot like CircleCI and Azure pipelines. You check in a yaml like file in a workflows directory.

I just realized that my account has access, but @metasys-server does not. So I just requested access for Metasys-server

**Comment by buldrinie** [comment]
I defined this workflow to build and test while pushing to the repo:

https://github.com/metasys-server/basic-services-dotnet/blob/master/.github/workflows/build-and-test.yml
