### ISSUE TITLE
Address Emanuel's comments on Phase 1 PR from savannah 

### ISSUE THREAD

**Issue by mgwelch** [metasys-server/basic-services-dotnet#18]
See #16 

-The current approach of TryLogin method needs an output parameter with an error code and message, e.g. the host is not reachable or the server returns a response different from 200 OK. The HTTP error message is expected to be shown to the SDK user in order to debug the login issue. When the client will call any methods of read/write but the access token is not available, i.e. login was not successful or not performed at all, a clear error about the bearer token missing must be provided.
Choosing this approach, should be consistent in all methods of Read/Write, e.g. TryReadProperty, TryGetObjectIdentifier, etc. Potentially every method that calls the server can fail with an error code. The important thing here is to not lose the response error, in such way SDK user can debug issues and log it.
In addition or alternatively we could provide a signature of the method where exception is raised, eg. Login, ReadProperty, etc. Providing both methods it is good, because it let the developer choose the approach to handle errors on the basis of the requirements.
In my experience using exceptions is easier, because in a multi-layered application you can manage it and/or throw that to the upper levels according to a defined strategy. On the other hand, using error codes management would delegate the logic to a conditional check and if it is not performed by the developer the program will continue in an abnormal state.

-It is ok to have HTTPS as requirement and default communication method, but I think that the SDK should be consistent with what REST API is exposing. At the moment, Metasys 10.1 Beta Build we have in the test VM has HTTP enabled and for the tests, I used it to overcome the expired certificate issue.
Take into consideration that the expired certification error is related to any of the methods called, not only the login. We could add a parameter on the constructor that by default is false, e.g. (IgnoreExpiredCertificate=false). In such way will be easier to handle all the subsequent calls and the developer can read it from a config file.

-The SDK should support a stateless environment where multiple connections are handled, e.g. a web server. The client SDK instance can be saved in the Application Pool (or its equivalent) and will be valid for all subsequent requests. I expect to have a property to understand if the SDK instance has a valid access token and the expiration date would be useful too. In this way if for any reason the refresh fails or the token is invalidated, the developer can call the login manually. I would expose the Access Token as well to give the chance to use it with your own rest client in combination with the SDK methods. This use case is related to the scenario where the SDK does not support a particular Metasys resource, i.e. the release of the API is prior than the client or the SDK development team decide to not support it at all.

-I think we should support asynchronous methods to make the SDK properly working for a Web Application. Consider the scenario where we have a browser client that access the Web Server that includes the SDK. Having blocking calls will drastically reduce the server performance and the throughput of the actual user requests served. Take into consideration that the underlying Flurl calls are asynchronous. We could just add an asynchronous version of the methods, e.g. ReadPropertyAsync, LoginAsync, etc. The latest versions of the .NET framework / .NET core made asynchronous support transparent and using the couple of keywords async/wait allows the developer to make it without any particular knowledge while the framework pulls all the strings.

**Comment by SavannahEvans** [comment]
I have addressed most of these points on their individual issue cards and created a pull request with solutions. The following may need more follow up:
* "The SDK should support a stateless environment where multiple connections are handled, e.g. a web server. The client SDK instance can be saved in the Application Pool (or its equivalent) and will be valid for all subsequent requests."
* Implement either throwing exceptions or returning error codes when an HTTP error occurs.

**Comment by mgwelch** [comment]
> "The SDK should support a stateless environment where multiple connections are handled, e.g. a web server. The client SDK instance can be saved in the Application Pool (or its equivalent) and will be valid for all subsequent requests."

@SavannahEvans  @buldrinie This seems out of scope. What we want is a suite of client side libraries to be able to call our API.

This comment seems to suggest we build a separate application. While this may be useful, it's outside the scope of this project.

**Comment by buldrinie** [comment]
Good work @SavannahEvans, the stateless environment is a common use case example, but of course the Application design and development is up to the SDK consumer. So this point is basically addressed with the implementation of the GetAccessToken method in your latest PR. 
For the error management, I'm going to deepen the topic to give a clear direction according to the best practice and put further comments  on the specific issue you created
https://github.com/metasys-server/basic-services-dotnet/issues/10
