### ISSUE TITLE
Implement Login method with an appropriate set of integration tests

### ISSUE THREAD

**Issue by mgwelch** [metasys-server/basic-services-dotnet#2]
Write the happy path test but also a few others:

* [x] bad username
* [x] bad hostname
* [x] bad password
* [x] invalid version (use raw number if needed)

**Comment by mgwelch** [comment]
To avoid dependency on a real server or OAS you can investigate mock servers

**Comment by SavannahEvans** [comment]
Since the login endpoint is versionless how should the program check that the version is okay?

**Comment by SavannahEvans** [comment]
> Since the login endpoint is versionless how should the program check that the version is okay?

Added automatic switch to version 2 if any other version is passed in.

**Comment by SavannahEvans** [comment]
Items left TODO:
* [ ] Use enum for versioning
* [ ] Implement login as it's own method
* [ ] Update request to use Flurl url building
