### ISSUE TITLE
Implement ReadPropertyMultiple method to use a response made with dynamics objects

### ISSUE THREAD

**Issue by buldrinie** [metasys-server/basic-services-dotnet#20]
The current method creates a response object for each attribute requested, causing a redundant JSON payload and making its usage difficult. The expected output is an array where each point is represented by an object comprehensive of all the attributes requested.

**Comment by SavannahEvans** [comment]
Issue addressed in #25. ReadPropertyMultiple now returns a IEnumerable<(Guid, IEnumerable<Variant>)>. Does this correct the issue?

**Comment by buldrinie** [comment]
It's ok for the object structure, but we need to rename item1 and item2 properties in Id and Attributes
![enumerable](https://user-images.githubusercontent.com/54939252/65526240-16a66900-def1-11e9-8f6d-56e385cef39b.JPG)

**Comment by SavannahEvans** [comment]
Issue addressed in #27.

**Comment by buldrinie** [comment]
@SavannahEvans apparently the new signature (Guid Id, IEnumerable<Variant> Variants) you put doesn't affect the object structure, still remains item1 and item2 properties.

**Comment by SavannahEvans** [comment]
@buldrinie the object can be accessed with the new signatures or by specifying Item1 or Item2. I do not see a way of getting rid of the Item1 and Item2 properties. Do you have a suggestion for a change?
![image](https://user-images.githubusercontent.com/37116226/65793465-8142e900-e12b-11e9-94e0-24d5d74fb549.png)

**Comment by buldrinie** [comment]
Apparently there is no way to get  names serialized using Tuples, because this kind of object is just a collection of values without properties and the access through names in the code is a C# 7 compiler overlay. What I suggest is just to create a typed object for the return value.

**Comment by SavannahEvans** [comment]
My understanding of what needs to be completed:
* Create a VariantMultiple struct that holds the Guid and list of Variants.
* Return this struct rather than the current tuple in ReadPropertyMultiple.

**Comment by buldrinie** [comment]
Correct, in this way the properties names of the struct will be retained while serializing the object.

**Comment by SavannahEvans** [comment]
Issue addressed in #35.
