### ISSUE TITLE
Fix unhandled exception on ReadPropertyMultiple method that receives an invalid identifier

### ISSUE THREAD

**Issue by buldrinie** [metasys-server/basic-services-dotnet#21]
ReadPropertyMultiple method throws an unhandled exception when an invalid identifier is passed as input

**Comment by buldrinie** [comment]
![1 ID NOT MANAGED](https://user-images.githubusercontent.com/54939252/65056715-a9835880-d971-11e9-8e04-a3ad3bbb6803.JPG)

**Comment by SavannahEvans** [comment]
Issue addressed in #25. Added catch for System.InvalidOperationException for ReadPropertyMultiple .
