### ISSUE TITLE
Fix ScheduleRefresh method to perform token expiration date check according to UTC time zone

### ISSUE THREAD

**Issue by buldrinie** [metasys-server/basic-services-dotnet#26]
![refresh token bug_s](https://user-images.githubusercontent.com/54939252/65427880-9827c980-de13-11e9-8bc1-e80d4a3de468.png)
The current token expiration comparison uses DateTime.Now, thus local time is used against a UTC expiration date. When we have local time zone greater than GMT, this results in a loop of RefreshToken calls since the token will be read as expired at every check. Vice versa, for time zones less than GMT the token will be read as valid when is already expired after 30 minutes.

**Comment by SavannahEvans** [comment]
Issue addressed in #25.
