### ISSUE TITLE
Register the dll for COM

### ISSUE THREAD

**Issue by buldrinie** [metasys-server/basic-services-dotnet#32]
Create a script that registers and un-registers the DLL for COM.

**Comment by buldrinie** [comment]
The initial idea was to distribute the COM DLL through a NuGet package, but they are strictly bound to a Visual Studio Solution and the Packages file. In conclusion, the approach we could use is just to distribute the COM is a zip file with the DLL and the script to register it. The script should copy the DLL in a path defined by us, e.g. "C:\ProgramData\Johnson Controls\Metasys API Services".

**Comment by mgwelch** [comment]
> The initial idea was to distribute the COM DLL through a NuGet package, but they are strictly bound to a Visual Studio Solution and the Packages file.

You can use nuget to create a package of anything. I've used it to distribute a set of JSON files. It is not the case that they need to be bound to a solution.

**Comment by buldrinie** [comment]
Very good, just tested the nuget cli to install the @jshanmm package. Definitely providing both way, NuGet as preferred and zip file as alternative for who don't have the packet manager installed.

**Comment by buldrinie** [comment]
@mgwelch, I automated the zip package creation with a bat script, including copy of the DLL's in a JCI predefined location and its registration. We may have issues with NuGet folder structure and package dependencies to locate the files needed.
