### ISSUE TITLE
GetNetworkDevices performance issue

### ISSUE THREAD

**Issue by buldrinie** [metasys-server/basic-services-dotnet#45]
GetNetworkDevices method performs for each element a GetType call (using full URL) to get the description. This results in a performance degration.

**Comment by buldrinie** [comment]
The total call time is about 190 s. The blank spaces of about 60 s between each page are consumed for the GetType calls performed for each element. In this timeline they are not tracked by fiddler because they are performed with a temporary Flurl client.
![Network devices](https://user-images.githubusercontent.com/54939252/67403429-30030980-f5b2-11e9-8f0d-cd48293288c2.JPG)

**Comment by mgwelch** [comment]
I agree. The original MSSDA didn't return description in `GetDeviceList` so I see no need to include it.

> **Results**
> The returned list of devices is a set of text values separated by commas in the following format:
> `<Item Reference>,<Node Classification>,<Object Type>`


this documents the only 3 required pieces of information for an MSSDA replacement.

**Comment by buldrinie** [comment]
I addressed the issue in this commit https://github.com/metasys-server/basic-services-dotnet/commit/daa8ac130a656e057e2147d651c1f7584d7500b2. Without the single items get type calls we got the response back in about 11 s.
![net device optimized](https://user-images.githubusercontent.com/54939252/67476301-13211180-f658-11e9-94fe-dd307769232a.JPG)
