### ISSUE TITLE
This code structuring isn't consumer friendly

### ISSUE THREAD

**Issue by mgwelch** [metasys-server/basic-services-dotnet#48]
https://github.com/metasys-server/basic-services-dotnet/blob/f1d936984908af6b5e4640f35d514281a97a279f/MetasysServices/Models/AccessToken.cs#L3

it's odd when you need to add multiple usings to call one method. With current layout (which seems to be popular with our developers) you need to add 4 using statements to login and call a method.

You'd never see this sort of organization in most professional packages. See Microsoft.

Your models should be in the same namespace in which they are mentioned. Same for exceptions. So `MetasysClient` can return models and throw exceptions. I shouldn't have to add 2 more usings to be able to refer to these types.

You can use these folders for code organization if you wish. But then in Visual Studio or Visual Studio Code look for the option to not use folders as the default namespace.

**Comment by SavannahEvans** [comment]
Addressed in #51.
