### ISSUE TITLE
Make it clear the ignoreCertificateErrors is not appropriate for production

### ISSUE THREAD

**Issue by mgwelch** [metasys-server/basic-services-dotnet#84]
In the README you include this paragraph:

> ignoreCertificateErrors: If your server does not have a valid certificate the MetasysClient will not behave as expected and will likely block the connection. Setting the ignoreCertificateErrors = true will ignore this error and make an insecure connection with the server. To avoid this problem ensure the Metasys server has a valid certificate.

I'd just add something like the following to impress upon devs that this should never be done on a production site.

> **WARNING:** You should not ignore certificate errors on a production site. Doing so puts your communication with the server at risk of a man-in-the-middle attack. 

Maybe link to the appropriate related security topic: man in the middle. Just trying to help our customers but also make it clear this setting shouldn't be used or needed on a properly configured server.

**Comment by buldrinie** [comment]
Added warning for both COM and Basic Services.

**Comment by buldrinie** [comment]
Added warning for both COM and Basic Services.
