### ISSUE TITLE
Add enumeration for NetworkDevice types

### ISSUE THREAD

**Issue by buldrinie** [metasys-server/basic-services-dotnet#99]
We want to create an enumeration for NetworkDevice types and this will be used as input for the related methods:

https://github.com/metasys-server/basic-services-dotnet/blob/e3d5c21d51ab502f6d25b8285ddad01ece5b084b/MetasysServices/MetasysClient.cs#L762-L783

We could look for an enumset on the Metasys dictionary that contains the list of all the device types.

**Comment by Federico-Artioli** [comment]
I committed the changes to solve this issue to the branch 'release-4.1'
